<?php
$active     = $block->isEnabled();
$autoload   = $block->isAutoLoad();

if ($active):

    $nextButtonText = $block->getNextButtonText();
    $prevButtonText = $block->getPrevButtonText();

    if ($autoload):
    ?>

    <style>#cg-infinite-loader-prev, #cg-infinite-loader-next{visibility: hidden;opacity: 0;}</style>

    <?php endif; ?>

    <div id="cg-infinite-loader">

        <div id="cg-infinite-loader-prev">
            <a class="cg-infinite-loader-prev action-primary"><?= $prevButtonText; ?></a>
        </div>

        <div id="cg-infinite-loader-next">
            <a class="cg-infinite-loader-next action-primary"><?= $nextButtonText;?></a>
        </div>

    </div>

    <script type="text/x-magento-init">
    {
        "#cg-infinite-loader": {
            "Codegenixuk_InfiniteScroll/js/cg-infinite-loader": {
                "active":"<?=$active;?>",
                "autoLoad":"<?=$autoload;?>"
            }
        }
    }
    </script>

<?php endif;?>

